Daring

In [1]:
import cv2
import numpy as np

create a black image 

In [2]:
image = np.zeros((512,512,3),np.uint8)
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
image

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [4]:
start_point  = (10,10)
end_point = (511,511)
color = (153,171,255)
thicknees = 10
cv2.line(image,start_point,end_point,color,thicknees)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [153, 171, 255],
        [153, 171, 255],
        [153, 171, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [153, 171, 255],
        [153, 171, 255],
        [153, 171, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [153, 171, 255],
        [153, 171, 255],
        [153, 171, 255]]

In [5]:
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
top_left_vertex = (384,210)
bottom_right_vertex = (510,120)
color = (0,115,170)
thicknees = 3
cv2.rectangle(image, top_left_vertex, bottom_right_vertex, color,thicknees)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [153, 171, 255],
        [153, 171, 255],
        [153, 171, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [153, 171, 255],
        [153, 171, 255],
        [153, 171, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [153, 171, 255],
        [153, 171, 255],
        [153, 171, 255]]

In [7]:
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
center_coordinates = (384,210)
radius = 63
color = (0,255,128)
thicknees = 2
cv2.circle(image,center_coordinates,radius, color,thicknees)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [153, 171, 255],
        [153, 171, 255],
        [153, 171, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [153, 171, 255],
        [153, 171, 255],
        [153, 171, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [153, 171, 255],
        [153, 171, 255],
        [153, 171, 255]]

In [9]:
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
text = 'what are you looking '
org = (10,500)
font = cv2.FONT_HERSHEY_SIMPLEX
font_scale = 1
color = (204,200,20)
thicknees = 3
cv2.putText(image,text,org,font,font_scale, color,thicknees)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [153, 171, 255],
        [153, 171, 255],
        [153, 171, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [153, 171, 255],
        [153, 171, 255],
        [153, 171, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [153, 171, 255],
        [153, 171, 255],
        [153, 171, 255]]

In [11]:

cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()