# importing libraries

In [1]:
import cv2
import numpy as np

# Reading an image

In [25]:
img = cv2.imread("C:\\Users\\aedpu\\OneDrive\\Pictures\\download (1).jpeg")
img

array([[[32, 30, 36],
        [32, 30, 36],
        [32, 30, 36],
        ...,
        [18, 17, 19],
        [18, 17, 19],
        [18, 17, 19]],

       [[32, 30, 36],
        [32, 30, 36],
        [32, 30, 36],
        ...,
        [18, 17, 19],
        [18, 17, 19],
        [18, 17, 19]],

       [[32, 30, 36],
        [32, 30, 36],
        [32, 30, 36],
        ...,
        [18, 17, 19],
        [18, 17, 19],
        [18, 17, 19]],

       ...,

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 1,  1,  1],
        ...,
        [ 0,  0,  0],
        [22, 22, 22],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 8,  8,  8],
        [ 9,  9,  9],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 8,  8,  8]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]], dtype=uint8)

# Display the image

In [26]:
cv2.imshow("Image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
shp = img.shape

In [28]:
shp

(233, 216, 3)

# size of an img

In [29]:
size = img.size

In [30]:
size

150984

# img reshape

In [31]:
reshape_image = cv2.resize(img,(700,700))

In [32]:
reshape_image.size

1470000

In [33]:
reshape_image.shape

(700, 700, 3)

In [34]:
cv2.imshow("Image",img)
cv2.imshow("Reshipe Image",reshape_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# value of pix

In [35]:
px = img[201,200]

In [36]:
img

array([[[32, 30, 36],
        [32, 30, 36],
        [32, 30, 36],
        ...,
        [18, 17, 19],
        [18, 17, 19],
        [18, 17, 19]],

       [[32, 30, 36],
        [32, 30, 36],
        [32, 30, 36],
        ...,
        [18, 17, 19],
        [18, 17, 19],
        [18, 17, 19]],

       [[32, 30, 36],
        [32, 30, 36],
        [32, 30, 36],
        ...,
        [18, 17, 19],
        [18, 17, 19],
        [18, 17, 19]],

       ...,

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 1,  1,  1],
        ...,
        [ 0,  0,  0],
        [22, 22, 22],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 8,  8,  8],
        [ 9,  9,  9],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 8,  8,  8]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]], dtype=uint8)

# ROI 

In [37]:
img1 = cv2.imread("C:\\Users\\aedpu\\OneDrive\\Pictures\\download.jpeg")

In [38]:
img1

array([[[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       ...,

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]]

In [39]:
#Select ROI
r = cv2.selectROI("Select the area " , img)

# crop img
cropped_image = img[int(r[1]):int(r[1]+r[3]),
                    int(r[0]):int(r[0]+r[2])]
cv2.imshow("cropped image",cropped_image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [40]:
cropped_image

array([[[ 30,  28,  34],
        [ 30,  28,  34],
        [ 30,  28,  34],
        ...,
        [ 88,  61, 111],
        [ 83,  78,  75],
        [ 78,  89,  51]],

       [[ 30,  28,  34],
        [ 30,  28,  34],
        [ 30,  28,  34],
        ...,
        [ 69,  82,  44],
        [ 94,  93, 103],
        [ 67,  67,  83]],

       [[ 30,  28,  34],
        [ 30,  28,  34],
        [ 30,  28,  34],
        ...,
        [ 52,  46,  69],
        [ 97, 105,  88],
        [ 82,  80,  92]],

       ...,

       [[ 25,  24,  26],
        [ 24,  23,  25],
        [ 27,  26,  28],
        ...,
        [115, 113, 113],
        [150, 148, 148],
        [187, 185, 185]],

       [[ 24,  23,  25],
        [ 23,  22,  24],
        [ 26,  25,  27],
        ...,
        [ 40,  38,  37],
        [ 14,  12,  11],
        [ 37,  35,  34]],

       [[ 24,  23,  25],
        [ 23,  22,  24],
        [ 26,  25,  27],
        ...,
        [ 98,  96,  95],
        [139, 137, 136],
        [160, 158, 157]]

In [41]:
cv2.imwrite('saveimage33.png',cropped_image)

True

In [44]:
img2 = cv2.imread("C:\\Users\\aedpu\\OneDrive\\Pictures\\download .3.jpeg")

In [47]:
b,g,r = cv2.split(img2)

# to display the split image
cv2.imshow('image',img2)
cv2.imshow('blue',b)
cv2.imshow('green',g)
cv2.imshow('red',r)
cv2.waitKey(0)
cv2.destroyAllWindows()