In [1]:
import cv2
import numpy as np

In [2]:
img_1 = cv2.imread("C:\\Users\\aedpu\\OneDrive\\Pictures\\Thanos.jpg")
img = cv2.resize(img_1,(512,512))
shp=img.shape
print(shp)
height,width=img.shape[:2]
print(height)
print(width)

(512, 512, 3)
512
512


In [3]:
cv2.imshow("IMG",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
center = (width/2,height/2)
print(center)

(256.0, 256.0)


In [5]:
rotate_matrix = cv2.getRotationMatrix2D(center= center, angle = 180 , scale = 1.0)
print(rotate_matrix)

[[-1.0000000e+00  1.2246468e-16  5.1200000e+02]
 [-1.2246468e-16 -1.0000000e+00  5.1200000e+02]]


In [6]:
rotate_image = cv2.warpAffine(src=img, M=rotate_matrix, dsize=(width,height))
cv2.imshow("ORG_Image",img)
cv2.waitKey(0)
cv2.imshow("rotate_image",rotate_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

translation

In [7]:
tx , ty = 100.0,50.0
print(tx)
print(ty)

100.0
50.0


In [8]:
translation_matrix = np.array([[1, 0 , tx],[0, 1, ty]])
print(translation_matrix)

[[  1.   0. 100.]
 [  0.   1.  50.]]


In [9]:
translation_image = cv2.warpAffine(src=img, M=translation_matrix, dsize=(width,height))

In [12]:
cv2.imshow("translation_matrix",translation_image)
cv2.waitKey(0)
cv2.destroyAllWindows()