In [1]:
import cv2
import numpy as np

# image reading

In [2]:
img1 = cv2.imread("C:\\Users\\aedpu\\OneDrive\\Pictures\\noise.jpeg")

In [3]:
cv2.imshow("Original",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
shp=img1.shape
print(shp)

(164, 308, 3)


# shape after resize

In [5]:
img = cv2.resize(img1,(720,720))

In [6]:
cv2.imwrite("C:\\Users\\aedpu\\OneDrive\\Pictures\\imgre.png",img)

True

In [7]:
shp=img.shape
print(shp)

(720, 720, 3)


In [8]:
cv2.imshow("resize",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# image filters

# image smoothing 2d convolution

# kernal

In [9]:
kernal =  np.ones((10,10),float)/100

In [10]:
print(kernal)

[[0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01]
 [0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01]
 [0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01]
 [0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01]
 [0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01]
 [0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01]
 [0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01]
 [0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01]
 [0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01]
 [0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01]]


# 2D Filtering display 

In [11]:
fillter2D = cv2.filter2D(img,-1,kernal)

In [12]:
fillter2D

array([[[ 6,  4,  4],
        [ 6,  4,  4],
        [ 6,  4,  4],
        ...,
        [10,  4,  5],
        [10,  4,  5],
        [10,  4,  5]],

       [[ 6,  4,  4],
        [ 6,  4,  4],
        [ 6,  4,  4],
        ...,
        [10,  4,  5],
        [10,  4,  5],
        [10,  4,  5]],

       [[ 6,  4,  4],
        [ 6,  4,  4],
        [ 6,  4,  4],
        ...,
        [10,  4,  5],
        [10,  4,  5],
        [10,  4,  5]],

       ...,

       [[13,  9, 23],
        [13,  9, 23],
        [13,  9, 23],
        ...,
        [15, 11, 17],
        [15, 11, 17],
        [15, 11, 17]],

       [[14,  9, 24],
        [14,  9, 24],
        [14,  9, 23],
        ...,
        [14, 10, 16],
        [14, 10, 16],
        [14, 10, 16]],

       [[14, 10, 24],
        [14, 10, 24],
        [14, 10, 24],
        ...,
        [14, 10, 16],
        [14, 10, 16],
        [14, 10, 16]]], dtype=uint8)

In [13]:
cv2.imshow("fillter2D",fillter2D)
cv2.imshow("Orginal",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# image Blurring 

In [14]:
blur = cv2.blur(img,(6,6))

In [15]:
blur

array([[[ 6,  4,  4],
        [ 6,  4,  4],
        [ 6,  4,  4],
        ...,
        [10,  4,  5],
        [10,  4,  5],
        [10,  4,  5]],

       [[ 6,  4,  4],
        [ 6,  4,  4],
        [ 6,  4,  4],
        ...,
        [10,  4,  5],
        [10,  4,  5],
        [10,  4,  5]],

       [[ 6,  4,  4],
        [ 6,  4,  4],
        [ 6,  4,  4],
        ...,
        [10,  4,  5],
        [10,  4,  5],
        [10,  4,  5]],

       ...,

       [[15, 10, 25],
        [15, 10, 25],
        [15, 10, 25],
        ...,
        [14, 10, 16],
        [14, 10, 16],
        [14, 10, 16]],

       [[17, 12, 26],
        [17, 12, 26],
        [16, 11, 26],
        ...,
        [14, 10, 16],
        [14, 10, 16],
        [14, 10, 16]],

       [[17, 12, 27],
        [17, 12, 27],
        [17, 12, 27],
        ...,
        [13,  9, 15],
        [13,  9, 15],
        [13,  9, 15]]], dtype=uint8)

In [16]:
cv2.imshow("blur",blur)
cv2.imshow("Orginal",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# image blurring - Gaussian image

In [17]:
img

array([[[ 6,  4,  4],
        [ 6,  4,  4],
        [ 6,  4,  4],
        ...,
        [10,  4,  5],
        [10,  4,  5],
        [10,  4,  5]],

       [[ 6,  4,  4],
        [ 6,  4,  4],
        [ 6,  4,  4],
        ...,
        [10,  4,  5],
        [10,  4,  5],
        [10,  4,  5]],

       [[ 6,  4,  4],
        [ 6,  4,  4],
        [ 6,  4,  4],
        ...,
        [10,  4,  5],
        [10,  4,  5],
        [10,  4,  5]],

       ...,

       [[15, 10, 25],
        [16, 11, 26],
        [18, 13, 28],
        ...,
        [13,  9, 15],
        [13,  9, 15],
        [13,  9, 15]],

       [[16, 11, 26],
        [17, 12, 26],
        [19, 14, 29],
        ...,
        [13,  9, 15],
        [13,  9, 15],
        [13,  9, 15]],

       [[16, 11, 26],
        [17, 12, 27],
        [19, 14, 29],
        ...,
        [13,  9, 15],
        [13,  9, 15],
        [13,  9, 15]]], dtype=uint8)

In [18]:
gauss = cv2.GaussianBlur(img,(5,5),4)

In [19]:
cv2.imshow("gauss",gauss)
cv2.imshow("Orginal",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# image blurring - median filter

In [20]:
img1 = cv2.imread("C:\\Users\\aedpu\\OneDrive\\Pictures\\Noise_salt_and_pepper.png")

In [21]:
med = cv2.medianBlur(img1,5)

In [22]:
cv2.imshow("med",med)
cv2.imshow("Orginal",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

# image blurring-  bilaterl filter

In [23]:
img2 = cv2.imread("C:\\Users\\aedpu\\OneDrive\\Pictures\\imgre.png")

In [32]:
bilat = cv2.bilateralFilter(img2,9,100,100)

In [33]:
cv2.imshow("fillter2D",fillter2D)
cv2.imshow("blur",blur)
cv2.imshow("gauss",gauss)
cv2.imshow("med",med)
cv2.imshow("bilat",bilat)
cv2.imshow("Orginal",img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [38]:
img3 = cv2.imread("C:\\Users\\aedpu\\OneDrive\\Pictures\\color.jpg")

In [39]:
bilat = cv2.bilateralFilter(img3,9,9,9)

color = cv2.bilateralFilter(img, 9, 250, 250) 
cartoon = cv2.bitwise_and(color, color, mask=edges)

cv2.imshow("bilat",bilat)
cv2.imshow("Orginal",img3)
cv2.waitKey(0)
cv2.destroyAllWindows()