# importing libraries

In [1]:
import cv2
import numpy as np

# Reading an image

In [2]:
img = cv2.imread("C:\\Users\\aedpu\\OneDrive\\Pictures\\download (1).jpeg")
img

array([[[32, 30, 36],
        [32, 30, 36],
        [32, 30, 36],
        ...,
        [18, 17, 19],
        [18, 17, 19],
        [18, 17, 19]],

       [[32, 30, 36],
        [32, 30, 36],
        [32, 30, 36],
        ...,
        [18, 17, 19],
        [18, 17, 19],
        [18, 17, 19]],

       [[32, 30, 36],
        [32, 30, 36],
        [32, 30, 36],
        ...,
        [18, 17, 19],
        [18, 17, 19],
        [18, 17, 19]],

       ...,

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 1,  1,  1],
        ...,
        [ 0,  0,  0],
        [22, 22, 22],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 8,  8,  8],
        [ 9,  9,  9],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 8,  8,  8]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]], dtype=uint8)

# Display the image

In [3]:
cv2.imshow("Image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
shp = img.shape

In [5]:
shp

(233, 216, 3)

# size of an img

In [6]:
size = img.size

In [7]:
size

150984

# img reshape

In [8]:
reshape_image = cv2.resize(img,(700,700))

In [9]:
reshape_image.size

1470000

In [10]:
reshape_image.shape

(700, 700, 3)

In [11]:
cv2.imshow("Image",img)
cv2.imshow("Reshipe Image",reshape_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# value of pix

In [12]:
px = img[201,200]

In [13]:
img

array([[[32, 30, 36],
        [32, 30, 36],
        [32, 30, 36],
        ...,
        [18, 17, 19],
        [18, 17, 19],
        [18, 17, 19]],

       [[32, 30, 36],
        [32, 30, 36],
        [32, 30, 36],
        ...,
        [18, 17, 19],
        [18, 17, 19],
        [18, 17, 19]],

       [[32, 30, 36],
        [32, 30, 36],
        [32, 30, 36],
        ...,
        [18, 17, 19],
        [18, 17, 19],
        [18, 17, 19]],

       ...,

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 1,  1,  1],
        ...,
        [ 0,  0,  0],
        [22, 22, 22],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 8,  8,  8],
        [ 9,  9,  9],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 8,  8,  8]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]], dtype=uint8)

# ROI 

In [14]:
img1 = cv2.imread("C:\\Users\\aedpu\\OneDrive\\Pictures\\download.jpeg")

In [15]:
img1

array([[[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       ...,

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]]

In [16]:
#Select ROI
r = cv2.selectROI("Select the area " , img)

# crop img
cropped_image = img[int(r[1]):int(r[1]+r[3]),
                    int(r[0]):int(r[0]+r[2])]
cv2.imshow("cropped image",cropped_image )
cv2.waitKey(0)
cv2.destroyAllWindows()


In [17]:
cropped_image

array([[[32, 30, 36],
        [32, 30, 36],
        [32, 30, 36],
        ...,
        [14, 14, 14],
        [14, 14, 14],
        [14, 14, 14]],

       [[32, 30, 36],
        [32, 30, 36],
        [32, 30, 36],
        ...,
        [14, 14, 14],
        [14, 14, 14],
        [14, 14, 14]],

       [[32, 30, 36],
        [32, 30, 36],
        [32, 30, 36],
        ...,
        [14, 14, 14],
        [14, 14, 14],
        [14, 14, 14]],

       ...,

       [[ 8,  8,  8],
        [ 6,  6,  6],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 5,  5,  5],
        [ 1,  1,  1]],

       [[ 0,  0,  0],
        [ 8,  8,  8],
        [ 0,  0,  0],
        ...,
        [18, 18, 18],
        [ 6,  6,  6],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]], dtype=uint8)

In [18]:
cv2.imwrite('saveimage33.png',cropped_image)

True

splitting an image

In [19]:
img2 = cv2.imread("C:\\Users\\aedpu\\OneDrive\\Pictures\\download .3.jpeg")

In [20]:
b,g,r = cv2.split(img2)

# to display the split image
cv2.imshow('image',img2)
cv2.imshow('blue',b)
cv2.imshow('green',g)
cv2.imshow('red',r)
cv2.waitKey(0)
cv2.destroyAllWindows()

merging an  image

In [27]:
mer = cv2.merge((r,g,r,g))

#displaying the mergin image

cv2.imshow('merge',mer)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
cv2.imwrite('mergin.png',mer)

True